/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a new game */
        post: operations["create_game_api_v1_games_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a game's current state */
        get: operations["get_game_api_v1_games__game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{game_id}/moves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Play a move for whoever's turn it is */
        post: operations["play_move_api_v1_games__game_id__moves_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BoardStatus
         * @description Status of one small board.
         * @enum {string}
         */
        BoardStatus: "open" | "x_won" | "o_won" | "draw";
        /**
         * ErrorOut
         * @description The one error shape every endpoint uses.
         */
        ErrorOut: {
            /**
             * Code
             * @example cell_occupied
             */
            code: string;
            /**
             * Detail
             * @example Cell 5 of board E is already taken.
             */
            detail: string;
        };
        /** GameOut */
        GameOut: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            status: components["schemas"]["GameStatus"];
            /** @description Whose turn it is; null once the game is over. */
            current_player: components["schemas"]["Player"] | null;
            /**
             * Forced Board
             * @description The board the current player must play in; null means a free move.
             */
            forced_board: number | null;
            /** Playable Boards */
            playable_boards: number[];
            /** Move Count */
            move_count: number;
            /** Boards */
            boards: components["schemas"]["SmallBoardOut"][];
        };
        /**
         * GameStatus
         * @enum {string}
         */
        GameStatus: "in_progress" | "x_won" | "o_won" | "draw";
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** MoveIn */
        MoveIn: {
            /** Board */
            board: number;
            /** Cell */
            cell: number;
        };
        /**
         * Player
         * @enum {string}
         */
        Player: "x" | "o";
        /** SmallBoardOut */
        SmallBoardOut: {
            /** Index */
            index: number;
            status: components["schemas"]["BoardStatus"];
            /** Cells */
            cells: (components["schemas"]["Player"] | null)[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_game_api_v1_games_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameOut"];
                };
            };
        };
    };
    get_game_api_v1_games__game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameOut"];
                };
            };
            /** @description No game with this id (`game_not_found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The request failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
    play_move_api_v1_games__game_id__moves_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameOut"];
                };
            };
            /** @description No game with this id (`game_not_found`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description A game rule refused the move: `game_over`, `board_not_playable`, `board_decided`, `cell_occupied`, or `move_conflict`. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description The request failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
        };
    };
}
